In [2]:
import random
secret = random.randint(0,100)

guessed = False
turns_left = 5
while (not guessed and turns_left > 0):
    print("guess a number between 0 and 100")

    guess = int(input("enter your guess: "))
    if guess == secret:
        print("WINNER!")
        guessed = True
    elif abs(guess - secret) <= 5:
        print("lava")
    elif abs(guess-secret) <= 20:
        print("warm")
    else:
        print("so so cold")
    
    turns_left -= 1

if not guessed:
    "You lost."

guess a number between 0 and 100
so so cold
guess a number between 0 and 100
warm
guess a number between 0 and 100
so so cold
guess a number between 0 and 100
lava
guess a number between 0 and 100
lava


In [4]:
x = 100
root = x/2
change = x/2

while (change > 0.1):
    old_root = root
    root = 0.5*(root + x/root)
    change = abs(root - old_root)

print(root)

10.000046356507898


In [10]:
import math
def estimatePi(n):
    estimate = 0
    for i in range(1, 2*n, 4):
        estimate += 4/i
    for i in range(3, 2*n, 4):
        estimate -= 4/i
    return estimate

def estimate_pi(tolerance):
    n = 0
    change = math.pi
    while (change > tolerance):
        n += 1
        change = abs(estimatePi(n) - estimatePi(n-1))
    
    print(estimatePi(n))

estimate_pi(0.1)


3.1891847822775965


In [16]:
data = [[3, 1, 6],
        [2, 8, 9],
        [5, 5, 5]]

print(data[:2][-1][::-1][0])
print(data[-1]) # takes just last element
print(data[:-1]) # takes everything but last element
print(data[::-1]) # reverses list

9
[[5, 5, 5], [2, 8, 9], [3, 1, 6]]


numpy

In [18]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])
print(vector)

[1 2 3 4 5]


In [22]:
print(np.zeros(3))
x = np.array([np.zeros(1), np.zeros(1), np.zeros(1)])
print(x)

[0. 0. 0.]
[[0.]
 [0.]
 [0.]]


In [24]:
y = np.array([np.zeros(3), np.zeros(3), np.zeros(3)])
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


magic square

In [28]:
def magic_square(array):
    arr = np.array(array)
    sum = np.sum(arr[0])
    print(sum)
    if (np.sum(arr[1]) == sum and np.sum(arr[2]) == sum and np.sum(arr[:, 0]) == sum and np.sum(arr[:, 1]) == sum and np.sum(arr[:, 2]) == sum and np.sum(np.diag(arr)) == sum and np.sum(np.diag(np.fliplr(arr))) == sum):
        return True
    else:
        return False

arr = [[8,1,6],[3,5,7],[4,9,2]]
print(magic_square(arr))


15
False


reading from a file

In [ ]:
filename = open('path', 'r')
filetext = filename.read()
filename.close()

for line in filename:
    print(line.strip())